version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: mostafa
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cinema_sys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
